on:
  push:
    branches:
      - '**'        # matches every branch
      - '!main'   # excludes master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: npm ci
      - run: npm run test:coverage
        env:
            MONGODB_URL: ${{ secrets.MONGODB_URL }}
            COOKIE_SECRET: ${{ secrets.COOKIE_SECRET }}
            MONGODB_DATABASE: ${{ secrets.MONGODB_DATABASE }}
      - name: Jest coverage report
        uses: ArtiomTr/jest-coverage-report-action@v2.0.8
      



