name: 'coverage'
on:
  push:
    branches:
      - '**'        # matches every branch
      - '!main'   # excludes master
jobs:
  coverage:
    permissions:
      checks: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ArtiomTr/jest-coverage-report-action@v2
        env:
          MONGODB_URL: ${{ secrets.MONGODB_URL }}
          COOKIE_SECRET: ${{ secrets.COOKIE_SECRET }}
          MONGODB_DATABASE: ${{ secrets.MONGODB_DATABASE }}


