on:
  push:
    branches:
      - '**'        # matches every branch
      - '!main'   # excludes master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          version: 16.x
      - run: npm ci
      - run: npm run test:coverage
        env:
            MONGODB_URL: ${{ secrets.MONGODB_URL }}
            COOKIE_SECRET: ${{ secrets.COOKIE_SECRET }}
            MONGODB_DATABASE: ${{ secrets.MONGODB_DATABASE }}
      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@1.1.3
        with:
            github-token: ${{ secrets.GITHUB_TOKEN }}



