name: RuneBuildGHA

on:
  push:
    branches:
      - GHARUNE

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: npm ci
      - name: Coveralls
        uses: coverallsapp/github-action@master
        env:
          NODE_COVERALLS_DEBUG: 1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: coverage/lcov.info
