on:
  push:
    branches:
      - '**'        # matches every branch
      - '!main'   # excludes master

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: install dependencies
        run: npm ci
      - run: npm test
      - name: Collect coverage
        uses: ArtiomTr/jest-coverage-report-action@v2
        env:
          MONGODB_URL: ${{ secrets.MONGODB_URL }}
          COOKIE_SECRET: ${{ secrets.COOKIE_SECRET }}
          MONGODB_DATABASE: ${{ secrets.MONGODB_DATABASE }}




